jobs:
  test_0:
    name: test_0
    runs-on: stream-8
    steps:
      - uses: "actions/checkout@v2"
      - run: sudo dnf -y install python3-pip
      - run: sudo bash runtests.sh

name: Greeting
on:
  push: {}
