jobs:
  test_0:
    name: test_0
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DUFFYY_SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: NO 
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - uses: "actions/checkout@v2"
      - run: sudo python3 -m pip install duffy fabric httpx
      - run: cd t_functional_duffy_runner/src && python3 __main__.py --arch=x86 --release=centos-8s

name: Greeting
on:
  push: {}
